# Generated by Django 4.2 on 2025-01-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Reklama nomi', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Reklama tavsifi', null=True)),
                ('video', models.FileField(help_text='Reklama uchun video', upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, help_text='Reklama faolmi?')),
            ],
        ),
    ]
